apiVersion: v1
kind: Pod
metadata: 
  name: roadsterpod
  labels:
    version: 1.0
spec:
  containers:
    - name: roadster
      image: techsriman/roadster:1.0
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /roadster/actuator/health/readiness
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /roadster/actuator/health/liveness
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3      