apiVersion: v1
kind: Pod
metadata:
  name: roadsterpod
  labels:
    app: roadster
    version: "1.0"
spec:
  containers:
    - name: roadster
      image: techsriman/roadster:3.0
      ports:
        - name: http
          containerPort: 8082
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8082
        initialDelaySeconds: 5
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8082
        initialDelaySeconds: 5
        timeoutSeconds: 5
        failureThreshold: 3    
      resources:
        requests:    
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1000m"  
          memory: "1024Mi"
      env:
        - name: preferences.originCountry
          valueFrom:
            configMapKeyRef:
              name: roadsterconfigmap
              key: origin-country
        - name: preferences.city
          valueFrom:
            configMapKeyRef:
              name: roadsterconfigmap
              key: city
        - name: preferences.age
          valueFrom:
            configMapKeyRef:
              name: roadsterconfigmap
              key: age
        - name: preferences.gender
          valueFrom:
            configMapKeyRef:
              name: roadsterconfigmap
              key: gender
        - name: preferences.internationalPlaces
          valueFrom:
            configMapKeyRef:
              name: roadsterconfigmap
              key: international-places   
      volumeMounts:
        - name: roadsterplacesvolume
          mountPath: "/config"
          readOnly: true

  volumes:
    - name: roadsterplacesvolume
      configMap:
        name: roadsterplacesconfigmap
        items:
          - key: places.properties              
            path: "places.properties"